
version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: akhil 
      POSTGRES_PASSWORD: akhil 
      POSTGRES_DB: timescale_data
    volumes:
      - timescale_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

volumes:
  timescale_data:
    driver: local
