export const cryptocurrencies = [
  { symbol: 'AAVE', name: 'Aave', image: '../images/aave.webp' },
  // { symbol: 'ACT', name: 'ACT', image: '../../public/images/act.webp' },
  { symbol: 'BLUR', name: 'Blur', image: '../../public/images/blur.webp' },
  { symbol: 'BOME', name: 'Book Of Meme', image: '../../public/images/bome.webp' },
  { symbol: 'BONK', name: 'Bonk', image: '../../public/images/bonk.webp' },
  { symbol: 'BTC', name: 'Bitcoin', image: '../../public/images/btc.webp' },
  { symbol: 'CLOUD', name: 'Sanctum', image: '../../public/images/cloud.png' },
  // { symbol: 'DBR', name: 'deBridge', image: '../../public/images/dbr.webp' },
  { symbol: 'DRIFT', name: 'Drift', image: '../../public/images/drift.webp' },
  { symbol: 'ENA', name: 'Ethena', image: '../../public/images/ena.webp' },
  { symbol: 'ETH', name: 'Ethereum', image: '../../public/images/eth.webp' },
  { symbol: 'GOAT', name: 'Goatseus Maximus', image: '../../public/images/goat.webp' },
  { symbol: 'HABIBI', name: 'Habibi Coin', image: '../../public/images/habibi.webp' },
  { symbol: 'HNT', name: 'Helium', image: '../../public/images/hnt.webp' },
  { symbol: 'HONEY', name: 'Hivemapper', image: '../../public/images/honey.webp' },
  { symbol: 'IO', name: 'io.net', image: '../../public/images/io.webp' },
  { symbol: 'JTO', name: 'Jito', image: '../../public/images/jto.webp' },
  { symbol: 'JUP', name: 'Jupiter', image: '../../public/images/jup.webp' },
  { symbol: 'KMNO', name: 'Kamino', image: '../../public/images/kmno.webp' },
  { symbol: 'LDO', name: 'Lido', image: '../../public/images/lido.webp' },
  { symbol: 'LINK', name: 'Chainlink', image: '../../public/images/link.webp' },
  { symbol: 'MAX', name: 'Matr1x', image: '../../public/images/max.webp' },
  { symbol: 'MEW', name: 'Cat in a dogs world', image: '../../public/images/mew.webp' },
  { symbol: 'ME', name: 'Magic Eden', image: '../../public/images/me.webp' },
  { symbol: 'MOBILE', name: 'Helium Mobile', image: '../../public/images/mobile.webp' },
  { symbol: 'MOODENG', name: 'Moo Deng', image: '../../public/images/moodeng.webp' },
  { symbol: 'MOTHER', name: 'Mother Iggy', image: '../../public/images/mother.webp' },
  //{ symbol: 'NYAN', name: 'Nyan Heroes', image: '../../public/images/nyan.webp' },
  { symbol: 'ONDO', name: 'Ondo', image: '../../public/images/ondo.webp' },
  { symbol: 'PENGU', name: 'Pudgy Penguins', image: '../../public/images/pengu.webp' },
  { symbol: 'PEPE', name: 'Pepe', image: '../../public/images/pepe.webp' },
  { symbol: 'POL', name: 'Polymath', image: '../../public/images/pol.webp' },
  { symbol: 'PRCL', name: 'Parcl', image: '../../public/images/prcl.webp' },
  { symbol: 'PYTH', name: 'PYTH', image: '../../public/images/pyth.webp' },
  //{ symbol: 'RAY', name: 'Raydium', image: '../../public/images/ray.webp' },
  { symbol: 'RENDER', name: 'Render', image: '../../public/images/render.webp' },
  { symbol: 'SHFL', name: 'Shuffle', image: '../../public/images/shfl.webp' },
  { symbol: 'SHIB', name: 'Shiba Inu', image: '../../public/images/shib.webp' },
  { symbol: 'SOL', name: 'Solana', image: '../../public/images/sol.webp' },
  { symbol: 'STRK', name: 'Starknet', image: '../../public/images/strk.webp' },
  { symbol: 'TNSR', name: 'Tensor', image: '../../public/images/tnsr.webp' },
  { symbol: 'UNI', name: 'Uniswap', image: '../../public/images/uni.webp' },
  { symbol: 'USDT', name: 'Tether', image: '../../public/images/usdt.webp' },
  { symbol: 'WEN', name: 'Wen', image: '../../public/images/wen.webp' },
  { symbol: 'WIF', name: 'Dogwifhat', image: '../../public/images/wif.webp' },
  { symbol: 'WLD', name: 'Worldcoin', image: '../../public/images/wld.webp' },
  { symbol: 'W', name: 'Wormhole', image: '../../public/images/w.webp' },
  { symbol: 'ZEX', name: 'Zeta', image: '../../public/images/zex.webp' },
  //{ symbol: 'ZKJ', name: 'Polyhedra Network', image: '../../public/images/zkj.webp' },
  { symbol: 'ZRO', name: 'LayerZero', image: '../../public/images/zro.webp' },
];
